
class Email:
    value: str

    def __init__(self, raw: str) -> None: ...
    def domain(self) -> str: ...
    def __repr__(self) -> str: ...

class NonEmptyStr:
    value: str

    def __init__(self, raw: str) -> None: ...
    def __repr__(self) -> str: ...

def send_email(to: Email, subject: NonEmptyStr, body: NonEmptyStr) -> None: ...
